spring:
  datasource:
    url:
    password:
    username:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect