spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:default-value}
    username: ${SPRING_DATASOURCE_USERNAME:default-value}
    password: ${SPRING_DATASOURCE_PASSWORD:default-value}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

my:
  encrypt_key: ${SPRING_ENCRYPTION_KEY_CARD_NUMBER:default-value}
  encryption_key: ${SPRING_ENCRYPTION_KEY_JWT:default-value}
  expired_in_days: 1

cors:
  allowed-origins:
    - "*" # permit all domains
  allowed-methods:
    - "*" # permit all http methods
  allowed-headers:
    - "*" # permit all headers